sudo: required
dist: xenial
language: c
compiler:
  - gcc

#env:

before_script:
   - echo before_script

script:
  - echo 'Message before fold' && echo -en 'travis_fold:start:test'
  - ls foobarbaz ; echo ls status is $? > status
  - echo 'travis_fold:end:test' && cat status

after_failure:
  - echo status
