sudo: required
dist: xenial
language: c
compiler:
  - gcc

#env:

before_script:
   - echo before_script

script:
  - echo 'Message before fold' && echo -en 'travis_fold:start:test\\r'
  - ls foobarbaz ; echo "Building mpy-cross status $?" > status
  - echo -en 'travis_fold:end:test\\r'
  - cat status

after_failure:
  - echo status
